DROP TABLE IF EXISTS penalties CASCADE;
DROP TABLE IF EXISTS points CASCADE;
DROP TABLE IF EXISTS event_registration CASCADE;
DROP TABLE IF EXISTS raw_times CASCADE;
DROP TABLE IF EXISTS run CASCADE;
DROP TABLE IF EXISTS car CASCADE;
DROP TABLE IF EXISTS car_class CASCADE;
DROP TABLE IF EXISTS event CASCADE;
DROP TABLE IF EXISTS driver CASCADE;
DROP TABLE IF EXISTS work_assignments CASCADE;
DROP TABLE IF EXISTS organization CASCADE;
DROP TABLE IF EXISTS user_role CASCADE;
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS role CASCADE;
DROP TABLE IF EXISTS region CASCADE;
DROP TABLE IF EXISTS season CASCADE;

-- also drops all of the notify_* triggers because they rely on this function
DROP FUNCTION notify_trigger() CASCADE;
