CREATE USER autoxtime WITH PASSWORD '@ut0XTime++';
GRANT ALL PRIVILEGES ON DATABASE autoxtime TO autoxtime;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO autoxtime;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO autoxtime;
