#ifndef AUTOXTIME_UTIL_H
#define AUTOXTIME_UTIL_H

#include <autoxtime/autoxtime.h>

#define AUTOXTIME_UTIL_NAMESPACE_BEG AUTOXTIME_NAMESPACE_BEG namespace util {
#define AUTOXTIME_UTIL_NAMESPACE_END AUTOXTIME_NAMESPACE_END }

#endif // AUTOXTIME_UTIL_H
