name: compile

on:
  push:
    branches: ['*']
    tags:
      - v*
  pull_request:
    type: [opened, reopened, edited]
  schedule:
    # run every night at midnight
    - cron:  '0 0 * * *'

jobs:
  compile:
    name: 'compile - ${{ matrix.os }} - ${{ matrix.compiler_c }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            qt_version: '5.12.2'
            apt_packages: >-
             mesa-common-dev libglu1-mesa-dev
             uwsgi uuid-dev libcap-dev libzmq3-dev libpwquality-dev libmemcached-dev libjemalloc-dev
            compiler_c: gcc
            compiler_cpp: c++
          - os: ubuntu-latest
            qt_version: '5.12.2'
            apt_packages: >-
             mesa-common-dev libglu1-mesa-dev
             uwsgi uuid-dev libcap-dev libzmq3-dev libpwquality-dev libmemcached-dev libjemalloc-dev
            compiler_c: clang
            compiler_cpp: clang++
    env:
      CC: '${{ matrix.compiler_c }}'
      CXX: '${{ matrix.compiler_cpp }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Cache Qt
        id: cache-qt
        uses: actions/cache@v2
        with:
          path: ../Qt
          key: ${{ runner.os }}-QtCache-${{ matrix.qt_version }}
      - name: Cache External Builds
        id: cache-external-cutelyst
        uses: actions/cache@v2
        with:
          path: |
            build/external-prefix
          key: ${{ runner.os }}-external-cutelyst-${{ hashFiles('cmake/*.cmake') }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: '${{ !steps.cache-qt.outputs.cache-hit }}'
          install-deps: '${{ !steps.cache-qt.outputs.cache-hit }}'
      - name: Install packages required for testing
        if: ${{ matrix.apt_packages }}
        run: |
          sudo apt-get -y install ${{ matrix.apt_packages }}
      - name: CMake Setup
        run: |
          cmake -S . -B build
      - name: Compile 
        run: |
          cmake --build build

# TODO figure out how to consolidate
  compile_windows:
    name: 'compile - ${{ matrix.os }} - ${{ matrix.compiler_c }}'
    runs-on: '${{ matrix.os }}'
    strategy:
      matrix:
        include:
          - os: windows-latest
            qt_version: '5.12.2'
            compiler_c: gcc
            compiler_cpp: c++
    env:
      CC: '${{ matrix.compiler_c }}'
      CXX: '${{ matrix.compiler_cpp }}'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        # windows specific
      - name: Setup MSYS/MinGW
        uses: msys2/setup-msys2@v2
        with:
          # use MinGW64 specifically so we can cross-compile
          msystem: MINGW64
          install: >-
            git
            base-devel
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-qt5
      - name: Cache External Builds
        id: cache-external-cutelyst
        uses: actions/cache@v2
        with:
          path: |
            build/external-prefix
          key: ${{ runner.os }}-external-cutelyst-${{ hashFiles('cmake/*.cmake') }}
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: ${{ matrix.qt_version }}
          cached: ${{ steps.cache-qt.outputs.cache-hit }}
          setup-python: '${{ !steps.cache-qt.outputs.cache-hit }}'
          install-deps: '${{ !steps.cache-qt.outputs.cache-hit }}'
      - name: CMake Setup
        shell: msys2 {0}
        run: |
          cmake -S . -B build -G "MSYS Makefiles"
      - name: Compile
        shell: msys2 {0}
        run: |
          cmake --build build
