name: static-analysis

on:
  push:
    branches: ['*']
    tags:
      - v*
  pull_request:
    type: [opened, reopened, edited]
  schedule:
    # run every night at midnight
    - cron:  '0 0 * * *'

jobs:
  cppcheck:
    name: 'static analysis - cppcheck'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install cppcheck
        run: |
          sudo apt-get -y install cppcheck
      - name: cppcheck
        run: |
          cppcheck src/
        
  clang-static-analyzer:
    name: 'static analysis - clang static analyzer'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: scan-build CMake Setup
        run: |
          scan-build cmake -S . -B build
      - name: scan-build Compile 
        run: |
          scan-build cmake --build build

