name: static-analysis

on:
  push:
    branches: ['*']
    tags:
      - v*
  pull_request:
    type: [opened, reopened, edited]
  schedule:
    # run every night at midnight
    - cron:  '0 0 * * *'

jobs:
  cppcheck:
    name: 'static analysis - cppcheck'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
      - name: Install cppcheck
        run: |
          sudo apt-get -y install cppcheck
      - name: cppcheck CMake Setup
        run: |
          cmake -S . -B build -DTEST_NAME=cppcheck
      - name: cppcheck
        run: |
          cmake --build build
        
  clang-static-analyzer:
    name: 'static analysis - clang static analyzer'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
      - name: Install clang-tools
        run: |
          sudo apt-get -y install clang-tools
      - name: scan-build CMake Setup
        run: |
          scan-build cmake -S . -B build
      - name: scan-build Compile 
        run: |
          scan-build cmake --build build

  clang-tidy:
    name: 'static analysis - clang tidy'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
      - name: Install clang-tools
        run: |
          sudo apt-get -y install clang-tools
      - name: clang-tidy CMake Setup
        run: |
          cmake -S . -B build -DTEST_NAME=clang-tidy
      - name: clang-tidy
        run: |
          cmake --build build

  include-what-you-use:
    name: 'static analysis - include what you use'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
      - name: Install iwyu
        run: |
          sudo apt-get -y install iwyu
      - name: iwyu CMake Setup
        run: |
          cmake -S . -B build -DTEST_NAME=iwyu
      - name: iwyu
        run: |
          cmake --build build

  link-what-you-use:
    name: 'static analysis - link what you use'
    runs-on: 'ubuntu-latest'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Install Qt
        uses: jurplel/install-qt-action@v2
        with:
          version: '5.12.2'
      - name: lwyu CMake Setup
        run: |
          cmake -S . -B build -DTEST_NAME=lwyu
      - name: lwyu
        run: |
          cmake --build build

